upstream backend_server {
    server web:8000;
}

server {
    listen 80;
    server_name localhost accounting.api.dronatandi.online;

    client_max_body_size 50M; # Strict support allocation parameters for financial receipt document attachments

    # Absolute Shared Media directory endpoints
    location /media/ {
        alias /var/www/media/;
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    # Absolute Static assets bundle endpoints
    location /static/ {
        alias /var/www/static/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location / {
        proxy_pass http://backend_server;
        proxy_http_version 1.1;
        
        # Live WebSockets bidirectional parameters channel activation matrices
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}