# Generated by Django 5.2.4 on 2026-05-21 03:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteLedger',
            fields=[
                ('tranno', models.AutoField(primary_key=True, serialize=False)),
                ('trdate', models.DateField(default=django.utils.timezone.now)),
                ('note_type', models.CharField(max_length=20)),
                ('note_no', models.CharField(max_length=50)),
                ('party_name', models.CharField(max_length=255)),
                ('party_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('trcr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('trdr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ctype', models.CharField(max_length=10)),
                ('delflag', models.CharField(default=' ', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialNoteHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('note_type', models.CharField(choices=[('DEBIT_NOTE', 'Debit Note (Purchase Return)'), ('CREDIT_NOTE', 'Credit Note (Sales Return)')], max_length=15)),
                ('note_date', models.DateField(default=django.utils.timezone.now)),
                ('original_invoice_no', models.CharField(blank=True, help_text='Original Bill Ref', max_length=100, null=True)),
                ('original_invoice_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('DAMAGED_GOODS', 'Damaged Goods'), ('RATE_DIFFERENCE', 'Rate Difference'), ('SALES_RETURN', 'Sales Return'), ('PURCHASE_RETURN', 'Purchase Return'), ('SHORTAGE', 'Shortage / Less Quantity')], max_length=30)),
                ('ewb_no', models.CharField(blank=True, max_length=50, null=True)),
                ('dispatch', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('total_pcs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_taxable', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('amtin_words', models.TextField(blank=True, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('delflag', models.CharField(default=' ', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.customermaster')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.suppliermaster')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialNoteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('hsncode', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cgst_p', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sgst_p', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('igst_p', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cgst_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igst_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transaction.financialnoteheader')),
            ],
        ),
    ]
