# Generated by Django 5.2.4 on 2026-05-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_noteledger_financialnoteheader_financialnotedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialnoteheader',
            name='created_by',
            field=models.CharField(default='ADMIN', max_length=100),
        ),
    ]
